# Generated by Django 5.1.15 on 2026-08-25 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push')], default='SMS', max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=20)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempts', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_messages', to='companies.company')),
            ],
            options={
                'db_table': 'notification_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationProviderConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push')], max_length=20)),
                ('provider_name', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sender_id', models.CharField(blank=True, default='', max_length=50)),
                ('settings_json', models.JSONField(blank=True, default=dict, help_text='Tenant preferences (non-secret settings)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_configs', to='companies.company')),
            ],
            options={
                'db_table': 'notification_provider_configs',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('PUSH', 'Push')], default='SMS', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('body_template', models.TextField(help_text='Template body with {{ variable }} placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='companies.company')),
            ],
            options={
                'db_table': 'notification_templates',
                'unique_together': {('company', 'code', 'channel')},
            },
        ),
    ]
