# Generated by Django 5.1.15 on 2026-08-26 22:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationproviderconfiguration',
            options={'ordering': ['priority', 'created_at']},
        ),
        migrations.RenameField(
            model_name='notificationmessage',
            old_name='content',
            new_name='rendered_content',
        ),
        migrations.RenameField(
            model_name='notificationproviderconfiguration',
            old_name='is_enabled',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='notificationmessage',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='notificationmessage',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='notificationmessage',
            name='provider_reference',
        ),
        migrations.RemoveField(
            model_name='notificationmessage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notificationproviderconfiguration',
            name='provider_name',
        ),
        migrations.AddField(
            model_name='notificationmessage',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmessage',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmessage',
            name='phone_normalized',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='notificationmessage',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmessage',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notificationproviderconfiguration',
            name='base_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='notificationproviderconfiguration',
            name='code',
            field=models.CharField(default='mock', help_text='Provider code e.g. beem, nextsms, mock', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationproviderconfiguration',
            name='encrypted_credentials',
            field=models.JSONField(blank=True, default=dict, help_text='Encrypted or secure provider credentials'),
        ),
        migrations.AddField(
            model_name='notificationproviderconfiguration',
            name='name',
            field=models.CharField(default='Mock Provider', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationproviderconfiguration',
            name='priority',
            field=models.PositiveIntegerField(default=10, help_text='Routing priority (lower number = higher priority)'),
        ),
        migrations.AddField(
            model_name='notificationproviderconfiguration',
            name='provider_type',
            field=models.CharField(choices=[('BEEM', 'Beem Africa'), ('NEXTSMS', 'NextSMS Tanzania'), ('MOCK', 'Mock SMS Provider')], default='MOCK', max_length=32),
        ),
        migrations.AddField(
            model_name='notificationproviderconfiguration',
            name='supports_delivery_receipts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='language',
            field=models.CharField(default='en', max_length=8),
        ),
        migrations.AlterField(
            model_name='notificationmessage',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='SMS', max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notificationmessage',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationproviderconfiguration',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='SMS', max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationproviderconfiguration',
            name='sender_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationproviderconfiguration',
            name='settings_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='body_template',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp')], default='SMS', max_length=16),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='code',
            field=models.CharField(help_text='Template code e.g. VOUCHER_CREATED', max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='notificationproviderconfiguration',
            table='notification_provider_configurations',
        ),
        migrations.CreateModel(
            name='NotificationDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_code', models.CharField(max_length=64)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=16)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=255)),
                ('provider_status', models.CharField(blank=True, default='', max_length=64)),
                ('failure_category', models.CharField(blank=True, default='', max_length=64)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='companies.company')),
                ('notification_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='notifications.notificationmessage')),
            ],
            options={
                'db_table': 'notification_delivery_attempts',
                'ordering': ['attempt_number'],
            },
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('company', 'code', 'channel', 'language')},
        ),
    ]
