# Generated by Django 5.1.15 on 2026-08-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationproviderconfiguration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationproviderconfiguration',
            name='provider_type',
            field=models.CharField(choices=[('BEEM', 'Beem Africa'), ('NEXTSMS', 'NextSMS Tanzania'), ('RAFIKISMS', 'RafikiSMS'), ('MOCK', 'Mock SMS Provider')], default='MOCK', max_length=32),
        ),
    ]
