# Generated by Django 5.1.15 on 2026-08-30 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('notifications', '0003_alter_notificationproviderconfiguration_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdeliveryattempt',
            name='sender_id',
            field=models.CharField(blank=True, default='', help_text='Sender ID snapshot used for this delivery attempt', max_length=64),
        ),
        migrations.AddField(
            model_name='notificationproviderconfiguration',
            name='default_sender_id',
            field=models.CharField(blank=True, default='', help_text='Default synced sender ID chosen by operator', max_length=32),
        ),
        migrations.AddField(
            model_name='notificationproviderconfiguration',
            name='last_sender_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationproviderconfiguration',
            name='code',
            field=models.CharField(help_text='Provider code e.g. beem, nextsms, rafikisms, mock', max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationproviderconfiguration',
            name='sender_id',
            field=models.CharField(blank=True, default='', help_text='Configured fallback/default sender ID', max_length=32),
        ),
        migrations.CreateModel(
            name='SMSProviderSenderID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_id', models.CharField(help_text='Alphanumeric sender ID e.g. USIMAMIZI', max_length=32)),
                ('external_id', models.CharField(blank=True, default='', help_text='Provider external sender ID UUID/ref', max_length=128)),
                ('display_name', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='active', max_length=32)),
                ('is_available', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_sender_ids', to='notifications.notificationproviderconfiguration')),
            ],
            options={
                'db_table': 'notification_provider_sender_ids',
                'ordering': ['-is_default', 'sender_id'],
                'unique_together': {('provider_configuration', 'sender_id')},
            },
        ),
        migrations.CreateModel(
            name='TenantSMSSenderPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_code', models.CharField(max_length=64)),
                ('sender_id', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_sender_preferences', to='companies.company')),
            ],
            options={
                'db_table': 'tenant_sms_sender_preferences',
                'unique_together': {('company', 'provider_code')},
            },
        ),
    ]
