# Generated by Django 5.1.15 on 2026-09-06 19:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0011_backfill_default_hotspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(choices=[('FREERADIUS', 'FreeRADIUS Daemon'), ('ROUTER_GATEWAY', 'MikroTik Router'), ('DATABASE', 'Primary Database'), ('SMS_GATEWAY', 'SMS Gateway')], db_index=True, max_length=32)),
                ('service_identifier', models.CharField(blank=True, default='', help_text="Identifier for instance, e.g. '127.0.0.1:1812' or Router IP '192.168.1.107'", max_length=128)),
                ('status', models.CharField(choices=[('HEALTHY', 'Healthy'), ('DEGRADED', 'Degraded'), ('DOWN', 'Down')], db_index=True, default='DOWN', max_length=16)),
                ('error_message', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('alert_count', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_incidents', to='companies.company')),
            ],
            options={
                'db_table': 'core_service_incidents',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemWatchdogConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True, help_text='Master toggle for watchdog probes and alerts.')),
                ('alert_phone_numbers', models.CharField(default='+255712345678', help_text='Comma-separated phone numbers in E.164 format to receive alert SMS (e.g. +255712345678,+255687654321)', max_length=255)),
                ('alert_cooldown_minutes', models.PositiveIntegerField(default=30, help_text='Minutes to suppress repeat SMS alerts during an active outage to prevent burning SMS credits.')),
                ('check_interval_seconds', models.PositiveIntegerField(default=60, help_text='Recommended polling interval for background daemon.')),
                ('radius_host', models.CharField(default='127.0.0.1', help_text='Host/IP of the FreeRADIUS server.', max_length=128)),
                ('radius_auth_port', models.PositiveIntegerField(default=1812, help_text='FreeRADIUS authentication UDP port.')),
                ('radius_secret', models.CharField(default='testing123', help_text='RADIUS shared secret for testing auth challenges.', max_length=128)),
                ('notify_on_recovery', models.BooleanField(default=True, help_text='Send a follow-up SMS when a downed service recovers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchdog_configs', to='companies.company')),
            ],
            options={
                'verbose_name': 'System Watchdog Configuration',
                'verbose_name_plural': 'System Watchdog Configurations',
                'db_table': 'core_system_watchdog_configs',
            },
        ),
    ]
