# Generated by Django 5.1.15 on 2026-08-26 22:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Company-unique short code for plan identifier', max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in specified currency', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('duration_value', models.PositiveIntegerField(default=1)),
                ('duration_unit', models.CharField(choices=[('HOURS', 'Hours'), ('DAYS', 'Days'), ('WEEKS', 'Weeks'), ('MONTHS', 'Months')], default='HOURS', max_length=16)),
                ('validity_mode', models.CharField(choices=[('CONTINUOUS', 'Continuous (Clock Time)'), ('USAGE_TIME', 'Usage Time (Active Consumption)'), ('CALENDAR', 'Calendar (Fixed End Date)')], default='CONTINUOUS', max_length=16)),
                ('download_speed_kbps', models.PositiveIntegerField(blank=True, help_text='Download bandwidth limit in Kbps', null=True)),
                ('upload_speed_kbps', models.PositiveIntegerField(blank=True, help_text='Upload bandwidth limit in Kbps', null=True)),
                ('data_limit_bytes', models.BigIntegerField(blank=True, help_text='Total data limit in bytes', null=True)),
                ('max_devices', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('simultaneous_sessions', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('idle_timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('session_timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='companies.company')),
            ],
            options={
                'db_table': 'plans',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
