# Generated by Django 5.1.15 on 2026-08-25 22:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiusAccountingLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('nas_ip', models.GenericIPAddressField(db_index=True)),
                ('mac_address', models.CharField(blank=True, default='', max_length=30)),
                ('framed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('packet_type', models.CharField(choices=[('Start', 'Start'), ('Interim-Update', 'Interim Update'), ('Stop', 'Stop')], max_length=30)),
                ('input_bytes', models.BigIntegerField(default=0)),
                ('output_bytes', models.BigIntegerField(default=0)),
                ('session_time', models.IntegerField(default=0, help_text='Session duration in seconds')),
                ('terminate_cause', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_logs', to='companies.company')),
            ],
            options={
                'db_table': 'radius_accounting_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RadiusClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nas_ip', models.GenericIPAddressField(db_index=True, unique=True)),
                ('nas_identifier', models.CharField(blank=True, default='', max_length=255)),
                ('secret', models.CharField(help_text='Shared RADIUS secret key', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radius_clients', to='companies.company')),
            ],
            options={
                'verbose_name': 'RADIUS Client',
                'verbose_name_plural': 'RADIUS Clients',
                'db_table': 'radius_clients',
            },
        ),
    ]
