# Generated by Django 5.1.15 on 2026-08-30 07:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('entitlements', '0001_initial'),
        ('radius', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiusaccountinglog',
            name='input_bytes',
        ),
        migrations.RemoveField(
            model_name='radiusaccountinglog',
            name='output_bytes',
        ),
        migrations.AlterUniqueTogether(
            name='radiusclient',
            unique_together={('company', 'nas_ip')},
        ),
        migrations.AddField(
            model_name='radiusaccountinglog',
            name='entitlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_logs', to='entitlements.accessentitlement'),
        ),
        migrations.AddField(
            model_name='radiusaccountinglog',
            name='input_gigawords',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='radiusaccountinglog',
            name='input_octets',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='radiusaccountinglog',
            name='nas_identifier',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='radiusaccountinglog',
            name='output_gigawords',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='radiusaccountinglog',
            name='output_octets',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='radiusaccountinglog',
            name='radius_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_logs', to='radius.radiusclient'),
        ),
        migrations.AddField(
            model_name='radiusaccountinglog',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='radiusaccountinglog',
            name='total_input_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='radiusaccountinglog',
            name='total_output_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='radiusclient',
            name='shared_secret_encrypted',
            field=models.TextField(blank=True, default='', help_text='Encrypted shared RADIUS secret key'),
        ),
        migrations.AlterField(
            model_name='radiusaccountinglog',
            name='mac_address',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='radiusclient',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radius_clients', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='radiusclient',
            name='nas_identifier',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='radiusclient',
            name='nas_ip',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.RemoveField(
            model_name='radiusclient',
            name='secret',
        ),
        migrations.CreateModel(
            name='EntitlementDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mac_address', models.CharField(db_index=True, max_length=32)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='entitlements.accessentitlement')),
            ],
            options={
                'db_table': 'entitlement_devices',
                'ordering': ['-first_seen_at'],
                'unique_together': {('entitlement', 'mac_address')},
            },
        ),
    ]
