# Generated by Django 5.1.15 on 2026-09-05 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radius', '0002_remove_radiusaccountinglog_input_bytes_and_more'),
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiusclient',
            name='router',
            field=models.OneToOneField(blank=True, help_text='Physical/logical router appliance hosting this RADIUS NAS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radius_client', to='routers.router'),
        ),
    ]
