# Generated by Django 5.1.15 on 2026-08-26 22:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(help_text='Unique batch reference e.g. VB-202608-000001', max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional batch issuance expiration date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_batches', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_batches', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_batches', to='plans.plan')),
            ],
            options={
                'db_table': 'voucher_batches',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'reference')},
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_code', models.CharField(db_index=True, help_text='Human readable voucher code e.g. K7PM-4XQ9', max_length=32)),
                ('code_hash', models.CharField(db_index=True, help_text='SHA256 hash of voucher code for secure lookup', max_length=64)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='AVAILABLE', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Issuance expiry date', null=True)),
                ('recipient_phone', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_by_customer', models.CharField(blank=True, default='', max_length=64)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='companies.company')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='plans.plan')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_vouchers', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='vouchers.voucherbatch')),
            ],
            options={
                'db_table': 'vouchers',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'display_code')},
            },
        ),
    ]
