# Generated by Django 5.1.15 on 2026-09-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='distribution_state',
            field=models.CharField(choices=[('UNSOLD', 'Unsold'), ('SOLD', 'Sold'), ('GIVEN_FREE', 'Given Free'), ('PROMOTIONAL', 'Promotional'), ('INTERNAL_TEST', 'Internal Test')], db_index=True, default='UNSOLD', max_length=32),
        ),
        migrations.AddField(
            model_name='voucher',
            name='export_status',
            field=models.CharField(choices=[('NOT_EXPORTED', 'Not Exported (Central SaaS)'), ('EXPORTED_ROUTEROS', 'Exported to RouterOS (Local Fallback)')], db_index=True, default='NOT_EXPORTED', max_length=32),
        ),
        migrations.AddField(
            model_name='voucher',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='distribution_mode',
            field=models.CharField(choices=[('UNSOLD', 'Unsold'), ('SOLD', 'Sold'), ('GIVEN_FREE', 'Given Free'), ('PROMOTIONAL', 'Promotional'), ('INTERNAL_TEST', 'Internal Test')], db_index=True, default='UNSOLD', max_length=32),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='export_status',
            field=models.CharField(choices=[('NOT_EXPORTED', 'Not Exported (Central SaaS)'), ('EXPORTED_ROUTEROS', 'Exported to RouterOS (Local Fallback)')], db_index=True, default='NOT_EXPORTED', max_length=32),
        ),
        migrations.AddField(
            model_name='voucherbatch',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Operator notes or distribution details'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='AVAILABLE', max_length=16),
        ),
    ]
