# Generated by Django 5.1.15 on 2026-09-02 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Main Wi-Fi HotSpot', max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('ssid', models.CharField(default='Usimamizi-WiFi-Lab', max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('brand_name', models.CharField(blank=True, default='', max_length=255)),
                ('headline', models.CharField(blank=True, default='Welcome to High-Speed Wi-Fi', max_length=255)),
                ('welcome_text', models.TextField(blank=True, default='Enter your access voucher code below to start browsing.')),
                ('primary_color', models.CharField(blank=True, default='#2563eb', max_length=32)),
                ('logo_url', models.URLField(blank=True, default='', max_length=512)),
                ('support_phone', models.CharField(blank=True, default='', max_length=64)),
                ('terms_url', models.URLField(blank=True, default='', max_length=512)),
                ('privacy_url', models.URLField(blank=True, default='', max_length=512)),
                ('default_language', models.CharField(choices=[('EN', 'English'), ('SW', 'Kiswahili')], default='EN', max_length=8)),
                ('router_login_url', models.CharField(default='http://10.5.50.1/login', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='companies.company')),
            ],
            options={
                'verbose_name': 'HotSpot Configuration',
                'verbose_name_plural': 'HotSpot Configurations',
                'db_table': 'hotspot_configurations',
                'ordering': ['name'],
            },
        ),
    ]
