# Generated by Django 5.1.15 on 2026-09-03 05:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_hotspotconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterUplinkProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Home Airtel 5G, Office Vodacom', max_length=128)),
                ('ssid', models.CharField(max_length=128)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uplink_profiles', to='companies.company')),
            ],
            options={
                'verbose_name': 'Router Uplink Profile',
                'verbose_name_plural': 'Router Uplink Profiles',
                'db_table': 'router_uplink_profiles',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
