# Generated by Django 5.1.15 on 2026-09-05 02:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_routeruplinkprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntiTetheringPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True, help_text='Master toggle to enforce Anti-Tethering protection.')),
                ('max_devices', models.PositiveIntegerField(default=1, help_text='Maximum authorized physical devices per entitlement.')),
                ('simultaneous_sessions', models.PositiveIntegerField(default=1, help_text='Maximum concurrent RADIUS sessions per voucher/account.')),
                ('ttl_lock_enabled', models.BooleanField(default=True, help_text='Enforce IPv4 downstream TTL lock to prevent tethered forwarding.')),
                ('ttl_lock_value', models.PositiveIntegerField(default=1, help_text='Target TTL value for downstream client packets (standard is 1).')),
                ('detect_ttl_63', models.BooleanField(default=True, help_text='Drop forwarded client packets from Android/iOS/macOS (TTL 63).')),
                ('detect_ttl_127', models.BooleanField(default=True, help_text='Drop forwarded client packets from Windows (TTL 127).')),
                ('strict_mode', models.BooleanField(default=False, help_text='Strict enforcement mode (experimental).')),
                ('ipv6_policy', models.CharField(choices=[('DISABLED', 'Disabled (Not Configured)'), ('BLOCK_IPV6', 'Block IPv6 Traffic'), ('FUTURE_MANAGED', 'Future Managed')], default='DISABLED', max_length=32)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_router_status', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anti_tethering_policies', to='companies.company')),
                ('hotspot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anti_tethering_policy', to='companies.hotspotconfiguration')),
            ],
            options={
                'verbose_name': 'Anti-Tethering Policy',
                'verbose_name_plural': 'Anti-Tethering Policies',
                'db_table': 'anti_tethering_policies',
                'ordering': ['-created_at'],
            },
        ),
    ]
