# Generated by Django 5.1.15 on 2026-09-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_backfill_infrastructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeruplinkprofile',
            name='password_encrypted',
            field=models.TextField(blank=True, default='', help_text='Encrypted upstream Wi-Fi password'),
        ),
    ]
