# Generated by Django 5.1.15 on 2026-09-05 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_encrypt_uplink_passwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeruplinkprofile',
            name='password',
        ),
    ]
