# Generated by Django 5.1.15 on 2026-09-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_remove_routeruplinkprofile_password'),
        ('locations', '0001_initial'),
        ('plans', '0002_alter_plan_duration_unit'),
        ('routers', '0002_router_health_message_router_last_health_check_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotconfiguration',
            name='is_default',
            field=models.BooleanField(db_index=True, default=False, help_text='Primary/default hotspot for the company'),
        ),
        migrations.AddField(
            model_name='hotspotconfiguration',
            name='plans',
            field=models.ManyToManyField(blank=True, help_text='Specific plans available on this hotspot. If empty, all active company plans are offered.', related_name='hotspots', to='plans.plan'),
        ),
        migrations.AddIndex(
            model_name='hotspotconfiguration',
            index=models.Index(fields=['company', 'is_default'], name='hotspot_con_company_a1fb16_idx'),
        ),
        migrations.AddConstraint(
            model_name='hotspotconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('company',), name='unique_default_hotspot_per_company'),
        ),
    ]
