# Generated by Django 5.1.15 on 2026-09-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_backfill_default_hotspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspotconfiguration',
            name='default_language',
            field=models.CharField(choices=[('EN', 'English'), ('SW', 'Kiswahili')], default='SW', max_length=8),
        ),
    ]
