# Generated by Django 5.1.15 on 2026-09-05 02:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_antitetheringpolicy'),
        ('plans', '0002_alter_plan_duration_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='Original raw phone entered by customer.', max_length=32)),
                ('normalized_phone', models.CharField(db_index=True, help_text='Canonical E.164 phone (+2557XXXXXXXX).', max_length=32)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=32)),
                ('language', models.CharField(choices=[('EN', 'English'), ('SW', 'Kiswahili')], default='EN', max_length=8)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-last_seen_at', '-created_at'],
                'unique_together': {('company', 'normalized_phone')},
            },
        ),
        migrations.CreateModel(
            name='CustomerOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=32)),
                ('otp_hash', models.CharField(help_text='Cryptographic hash of the 6-digit OTP.', max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_otps', to='companies.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otps', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer OTP',
                'verbose_name_plural': 'Customer OTPs',
                'db_table': 'customer_otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSubscriptionSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grace_period_minutes', models.PositiveIntegerField(default=30, help_text='Minutes customer remains in GRACE before permanent session disconnect.')),
                ('otp_expiry_minutes', models.PositiveIntegerField(default=5, help_text='Validity window for 6-digit SMS OTP.')),
                ('otp_resend_cooldown_seconds', models.PositiveIntegerField(default=60, help_text='Cooldown seconds before requesting a new OTP.')),
                ('remind_1day_before', models.BooleanField(default=True, help_text='Send SMS reminder 24 hours before expiration.')),
                ('remind_1hour_before', models.BooleanField(default=True, help_text='Send SMS reminder 1 hour before expiration.')),
                ('remind_at_expiry', models.BooleanField(default=True, help_text='Send SMS notification at expiration.')),
                ('allow_self_service', models.BooleanField(default=True, help_text='Allow customers to view portal and trigger manual renewals.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_settings', to='companies.company')),
            ],
            options={
                'verbose_name': 'Customer Subscription Settings',
                'verbose_name_plural': 'Customer Subscription Settings',
                'db_table': 'customer_subscription_settings',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('ACTIVE', 'Active'), ('GRACE', 'Grace Period'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=32)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('grace_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_mode', models.CharField(choices=[('MANUAL', 'Manual Renewal'), ('AUTO_RENEW_FUTURE', 'Auto-Renew (Future)')], default='MANUAL', max_length=32)),
                ('source', models.CharField(choices=[('SELF_SERVICE_PAYMENT', 'Self-Service Mobile Money'), ('ADMIN_CREATED', 'Administrator Created'), ('VOUCHER_UPGRADE', 'Voucher Upgrade'), ('PROMOTIONAL', 'Promotional Grant'), ('MANUAL', 'Manual Grant')], default='SELF_SERVICE_PAYMENT', max_length=32)),
                ('plan_snapshot', models.JSONField(blank=True, default=dict, help_text='Frozen snapshot of Plan commercial terms at activation/renewal.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='companies.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customers.customer')),
                ('hotspot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='companies.hotspotconfiguration')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-current_period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVATED', 'Activated'), ('RENEWED', 'Renewed'), ('GRACE_ENTERED', 'Grace Period Entered'), ('SUSPENDED', 'Suspended'), ('REACTIVATED', 'Reactivated'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, max_length=32)),
                ('old_status', models.CharField(blank=True, default='', max_length=32)),
                ('new_status', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_actions', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='customers.subscription')),
            ],
            options={
                'verbose_name': 'Subscription Event',
                'verbose_name_plural': 'Subscription Events',
                'db_table': 'subscription_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mac_address', models.CharField(db_index=True, help_text='Normalized MAC address AA:BB:CC:DD:EE:FF', max_length=32)),
                ('device_name', models.CharField(blank=True, default='', max_length=128)),
                ('device_type', models.CharField(choices=[('MOBILE', 'Mobile Phone'), ('LAPTOP', 'Laptop / PC'), ('TABLET', 'Tablet'), ('OTHER', 'Other Device')], default='MOBILE', max_length=32)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_trusted', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_devices', to='companies.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Customer Device',
                'verbose_name_plural': 'Customer Devices',
                'db_table': 'customer_devices',
                'ordering': ['-last_seen_at'],
                'unique_together': {('customer', 'mac_address')},
            },
        ),
    ]
