# Generated by Django 5.1.15 on 2026-09-05 03:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_antitetheringpolicy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Company-unique short code for location identifier (e.g. LOC-DAR-001)', max_length=64)),
                ('region', models.CharField(blank=True, default='', help_text='e.g. Dar es Salaam, Arusha, Mwanza', max_length=128)),
                ('district', models.CharField(blank=True, default='', help_text='e.g. Ilala, Kinondoni, Arusha City', max_length=128)),
                ('address', models.TextField(blank=True, default='', help_text='Street address or physical landmark')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(default='Africa/Dar_es_Salaam', max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance')], db_index=True, default='ACTIVE', max_length=32)),
                ('contact_person', models.CharField(blank=True, default='', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='companies.company')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'locations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'status'], name='locations_company_264789_idx'), models.Index(fields=['company', 'name'], name='locations_company_0b8f5f_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='unique_company_location_code')],
            },
        ),
    ]
