# Generated by Django 5.1.15 on 2026-09-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_backfill_default_hotspot'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='external_reference',
            field=models.CharField(blank=True, default='', help_text='ERP, CRM, or client billing code', max_length=128),
        ),
        migrations.AddField(
            model_name='location',
            name='installation_date',
            field=models.DateField(blank=True, help_text='Date the venue or infrastructure was commissioned', null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='operating_hours',
            field=models.CharField(blank=True, default='', help_text='Operating schedule e.g. 24/7, 08:00 - 22:00', max_length=128),
        ),
        migrations.AddField(
            model_name='location',
            name='site_type',
            field=models.CharField(blank=True, choices=[('BRANCH', 'Branch'), ('HOTEL', 'Hotel'), ('RESTAURANT', 'Restaurant'), ('CAFE', 'Café'), ('BUS_TERMINAL', 'Bus Terminal'), ('MALL', 'Shopping Mall'), ('OFFICE', 'Office'), ('PUBLIC_SITE', 'Public Site'), ('OTHER', 'Other')], db_index=True, default='OTHER', help_text='Operational deployment classification (e.g. BRANCH, HOTEL, MALL)', max_length=32),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['company', 'is_active'], name='locations_company_8ab559_idx'),
        ),
    ]
