# Generated by Django 5.1.15 on 2026-09-03 00:00

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_hotspotconfiguration'),
        ('entitlements', '0001_initial'),
        ('plans', '0001_initial'),
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('SNIPPE', 'Snippe'), ('MANUAL', 'Manual')], default='SNIPPE', max_length=32)),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('signature', models.CharField(blank=True, default='', max_length=512)),
                ('payload', models.JSONField(default=dict)),
                ('is_processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_webhook_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, help_text='Customer reference e.g. PUR-20260903-XXXXXX', max_length=64, unique=True)),
                ('customer_phone', models.CharField(db_index=True, help_text='Customer E.164 phone number', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAID', 'Paid'), ('ENTITLEMENT_CREATED', 'Entitlement Created'), ('FULFILLED', 'Fulfilled'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='CREATED', max_length=32)),
                ('client_mac', models.CharField(blank=True, default='', max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_purchases', to='companies.company')),
                ('entitlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='entitlements.accessentitlement')),
                ('hotspot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='companies.hotspotconfiguration')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='plans.plan')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='vouchers.voucher')),
            ],
            options={
                'db_table': 'access_purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotspotWalledGardenEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('DOMAIN', 'Domain (dst-host)'), ('IP', 'IP Address'), ('CIDR', 'CIDR Subnet')], default='DOMAIN', max_length=32)),
                ('host', models.CharField(blank=True, default='', help_text='Domain name e.g. api.snippe.sh', max_length=255)),
                ('address', models.CharField(blank=True, default='', help_text='IP or CIDR for walled-garden ip', max_length=255)),
                ('protocol', models.CharField(blank=True, default='', max_length=16)),
                ('port', models.CharField(blank=True, default='', max_length=16)),
                ('purpose', models.CharField(choices=[('PORTAL', 'Captive Portal'), ('PAYMENT', 'Payment Provider'), ('SYSTEM', 'System Infrastructure'), ('CUSTOM', 'Custom')], default='PAYMENT', max_length=32)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walled_garden_entries', to='companies.company')),
                ('hotspot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='walled_garden_entries', to='companies.hotspotconfiguration')),
            ],
            options={
                'db_table': 'hotspot_walled_garden_entries',
                'ordering': ['purpose', 'host', 'address'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('SNIPPE', 'Snippe'), ('MANUAL', 'Manual')], default='SNIPPE', max_length=32)),
                ('is_enabled', models.BooleanField(default=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=16)),
                ('api_base_url', models.URLField(default='https://api.snippe.sh')),
                ('api_key_encrypted', models.TextField(blank=True, default='', help_text='Encrypted API key for provider')),
                ('webhook_secret_encrypted', models.TextField(blank=True, default='', help_text='Encrypted webhook signature secret')),
                ('default_currency', models.CharField(default='TZS', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_configs', to='companies.company')),
            ],
            options={
                'verbose_name': 'Payment Provider Configuration',
                'db_table': 'payment_provider_configurations',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('SNIPPE', 'Snippe'), ('MANUAL', 'Manual')], default='SNIPPE', max_length=32)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('internal_reference', models.CharField(db_index=True, help_text='Transaction reference e.g. TXN-20260903-XXXXXX', max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=32)),
                ('payment_method', models.CharField(blank=True, default='mobile', max_length=64)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=32)),
                ('checkout_url', models.URLField(blank=True, default='', max_length=512)),
                ('payment_link_url', models.URLField(blank=True, default='', max_length=512)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='companies.company')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.accesspurchase')),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Snippe max 30-char idempotency key', max_length=30)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payments.paymenttransaction')),
            ],
            options={
                'db_table': 'payment_attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='accesspurchase',
            index=models.Index(fields=['company', 'status'], name='access_purc_company_e7f52e_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspurchase',
            index=models.Index(fields=['customer_phone', 'status'], name='access_purc_custome_2e36eb_idx'),
        ),
        migrations.AddIndex(
            model_name='accesspurchase',
            index=models.Index(fields=['reference'], name='access_purc_referen_7474c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentproviderconfiguration',
            unique_together={('company', 'provider')},
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['company', 'status'], name='payment_tra_company_252f02_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['provider_reference'], name='payment_tra_provide_73d4ff_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['internal_reference'], name='payment_tra_interna_1d6197_idx'),
        ),
    ]
