# Generated by Django 5.1.15 on 2026-09-05 03:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_antitetheringpolicy'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human label e.g. Kariakoo-Main-GW', max_length=255)),
                ('identity', models.CharField(blank=True, default='', help_text='MikroTik system identity (/system identity)', max_length=255)),
                ('vendor', models.CharField(default='MikroTik', max_length=64)),
                ('model', models.CharField(blank=True, default='', help_text='e.g. hAP ac lite, RB4011iGS+', max_length=128)),
                ('serial_number', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('management_ip', models.GenericIPAddressField(help_text='IP address used for RouterOS API / WinBox management')),
                ('api_port', models.PositiveIntegerField(default=8728, help_text='RouterOS API port (8728 for plain, 8729 for TLS)')),
                ('use_tls', models.BooleanField(default=False, help_text='Use RouterOS API-SSL encrypted connection')),
                ('api_username', models.CharField(default='admin', max_length=128)),
                ('api_password_encrypted', models.TextField(blank=True, default='', help_text='Encrypted RouterOS API management password')),
                ('routeros_version', models.CharField(blank=True, default='', help_text='e.g. 7.15.2', max_length=64)),
                ('architecture', models.CharField(blank=True, default='', help_text='e.g. mipsbe, arm64, x86_64', max_length=64)),
                ('firmware_version', models.CharField(blank=True, default='', max_length=64)),
                ('health_status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('DEGRADED', 'Degraded'), ('UNREACHABLE', 'Unreachable'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('system_resources', models.JSONField(blank=True, default=dict, help_text='Latest cached telemetry snapshot (cpu_load, free_memory, uptime, etc.)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='companies.company')),
                ('location', models.ForeignKey(help_text='Physical location where router is deployed', on_delete=django.db.models.deletion.PROTECT, related_name='routers', to='locations.location')),
            ],
            options={
                'verbose_name': 'Router',
                'verbose_name_plural': 'Routers',
                'db_table': 'routers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'location'], name='routers_company_2314ff_idx'), models.Index(fields=['company', 'health_status'], name='routers_company_1eff13_idx'), models.Index(fields=['management_ip'], name='routers_managem_e828f6_idx')],
            },
        ),
    ]
