# Generated by Django 5.1.15 on 2026-09-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='router',
            name='health_message',
            field=models.TextField(blank=True, default='', help_text='Diagnostic message from last health check'),
        ),
        migrations.AddField(
            model_name='router',
            name='last_health_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='router',
            name='uplink_interface_name',
            field=models.CharField(blank=True, default='wlan2', help_text='Default upstream station/WAN wireless interface name (e.g. wlan2, ether1)', max_length=64),
        ),
    ]
