# Generated by Django 5.1.15 on 2026-08-30 07:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('plans', '0001_initial'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('VOUCHER', 'Voucher'), ('MANUAL', 'Manual Grant'), ('PAYMENT', 'Direct Payment'), ('PROMOTION', 'Promotion'), ('ADMIN', 'Administrator')], default='VOUCHER', max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='PENDING', max_length=32)),
                ('reference', models.CharField(db_index=True, help_text='Human-readable entitlement code e.g. ENT-20260830-XXXXXX', max_length=64, unique=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('validity_mode', models.CharField(default='CONTINUOUS', max_length=32)),
                ('download_speed_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('upload_speed_kbps', models.PositiveIntegerField(blank=True, null=True)),
                ('data_limit_bytes', models.BigIntegerField(blank=True, null=True)),
                ('data_used_bytes', models.BigIntegerField(default=0)),
                ('usage_time_limit_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_time_used_seconds', models.PositiveIntegerField(default=0)),
                ('max_devices', models.PositiveIntegerField(default=1)),
                ('simultaneous_sessions', models.PositiveIntegerField(default=1)),
                ('idle_timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('session_timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('plan_snapshot', models.JSONField(default=dict, help_text='Frozen snapshot of Plan commercial properties at creation.')),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True, default='')),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entitlements', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_entitlements', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='plans.plan')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_entitlements', to=settings.AUTH_USER_MODEL)),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_entitlements', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.OneToOneField(blank=True, help_text='One-to-one constraint: A voucher can yield maximum 1 access entitlement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlement', to='vouchers.voucher')),
            ],
            options={
                'db_table': 'access_entitlements',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_used_bytes__gte', 0)), name='check_data_used_non_negative'), models.CheckConstraint(condition=models.Q(('usage_time_used_seconds__gte', 0)), name='check_usage_time_used_non_negative'), models.CheckConstraint(condition=models.Q(('max_devices__gte', 1)), name='check_max_devices_gte_1'), models.CheckConstraint(condition=models.Q(('simultaneous_sessions__gte', 1)), name='check_simultaneous_sessions_gte_1')],
            },
        ),
    ]
