# Generated by Django 5.1.15 on 2026-09-05 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('entitlements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessentitlement',
            name='consumer',
            field=models.ForeignKey(blank=True, help_text='Optional end-consumer identity holding this entitlement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='accessentitlement',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Optional commercial subscription lifecycle contract generating this entitlement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='customers.subscription'),
        ),
    ]
