# Generated by Django 5.1.15 on 2026-08-30 07:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('entitlements', '0001_initial'),
        ('radius', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acct_session_id', models.CharField(db_index=True, max_length=255)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('mac_address', models.CharField(db_index=True, max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('STOPPED', 'Stopped'), ('STALE', 'Stale')], db_index=True, default='ACTIVE', max_length=32)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_accounting_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('input_bytes', models.BigIntegerField(default=0, help_text='Total client upload bytes in session')),
                ('output_bytes', models.BigIntegerField(default=0, help_text='Total client download bytes in session')),
                ('session_seconds', models.PositiveIntegerField(default=0, help_text='Elapsed session connection time in seconds')),
                ('termination_reason', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_sessions', to='companies.company')),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='entitlements.accessentitlement')),
                ('radius_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='radius.radiusclient')),
            ],
            options={
                'db_table': 'hotspot_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='hotspot_ses_company_746430_idx'), models.Index(fields=['entitlement', 'status'], name='hotspot_ses_entitle_d25d90_idx'), models.Index(fields=['radius_client', 'acct_session_id'], name='hotspot_ses_radius__66641e_idx')],
            },
        ),
    ]
