# Generated by Django 5.1.15 on 2026-09-02 20:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('hotspot_sessions', '0001_initial'),
        ('radius', '0002_remove_radiusaccountinglog_input_bytes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDisconnectRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('MANUAL', 'Manual Admin Action'), ('ENTITLEMENT_SUSPENDED', 'Entitlement Suspended'), ('ENTITLEMENT_REVOKED', 'Entitlement Revoked'), ('DATA_QUOTA_EXHAUSTED', 'Data Quota Exhausted'), ('USAGE_TIME_EXHAUSTED', 'Usage Time Exhausted'), ('ADMIN_SECURITY_ACTION', 'Admin Security Action')], db_index=True, default='MANUAL', max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('ACKNOWLEDGED', 'Acknowledged'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=32)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('requested_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('response_code', models.CharField(blank=True, default='', max_length=64)),
                ('response_message', models.TextField(blank=True, default='')),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disconnect_requests', to='companies.company')),
                ('hotspot_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disconnect_requests', to='hotspot_sessions.hotspotsession')),
                ('radius_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disconnect_requests', to='radius.radiusclient')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_disconnects_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_disconnect_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='session_dis_company_155329_idx'), models.Index(fields=['hotspot_session', 'status'], name='session_dis_hotspot_8fb441_idx'), models.Index(fields=['requested_at'], name='session_dis_request_1fc55f_idx')],
            },
        ),
    ]
