# Generated by Django 5.1.15 on 2026-09-05 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('hotspot_sessions', '0002_sessiondisconnectrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotsession',
            name='consumer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspot_sessions', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='hotspotsession',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspot_sessions', to='customers.customerdevice'),
        ),
        migrations.AddField(
            model_name='hotspotsession',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspot_sessions', to='customers.subscription'),
        ),
    ]
