# Generated by Django 5.1.15 on 2026-09-05 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_hotspotconfiguration_is_default_and_more'),
        ('customers', '0001_initial'),
        ('entitlements', '0002_accessentitlement_consumer_and_more'),
        ('hotspot_sessions', '0003_hotspotsession_consumer_hotspotsession_device_and_more'),
        ('radius', '0003_radiusclient_router'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotsession',
            name='hotspot',
            field=models.ForeignKey(blank=True, help_text='Attributed HotSpot configuration for session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='companies.hotspotconfiguration'),
        ),
        migrations.AddIndex(
            model_name='hotspotsession',
            index=models.Index(fields=['hotspot', 'status'], name='hotspot_ses_hotspot_5d5bc2_idx'),
        ),
    ]
