# Generated by Django 5.1.15 on 2026-09-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotspot_sessions', '0004_hotspotsession_hotspot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspotsession',
            name='device_name',
            field=models.CharField(blank=True, default='', help_text='Hostname or friendly device label e.g. Fsociety, iPhone-13', max_length=128),
        ),
    ]
